### ISSUE TITLE
Develop & Improve UI/UX

### ISSUE THREAD

**Issue by Safnaj** [Safnaj/Github-User-Finder#2]

**Comment by HooriaHIC** [comment]
I'd like to work on this issue 😊

**Comment by Vlad412** [comment]
Hello ! I would like to contribute 🙂

**Comment by shashwatah** [comment]
Hey, I just made a pull request for this issue. Please take a look.

**Comment by Safnaj** [comment]
<div>
<img src="https://user-images.githubusercontent.com/37530024/96332401-61a59800-1081-11eb-9add-0feced8e48fe.png" width="280" height="280"/>
</div>
